version: '2'
services:
  postgres:
    image: postgres:9.6.0
    environment:
      POSTGRES_USER: lebowski
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    image: aackerman/lebowski-api
    entrypoint:
      - /bin/sh
      - production.sh
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
volumes:
  pgdata:
